CLIENT_ID = 'AVyXuEcUaLic5bDwf-w8qHsLXyMyi22huuwkDyXgH3ktpYwwobGh_pFNnKcshOuX4VzfK1ZZVpl1O0hX'
CLIENT_SECRET = 'EL9YhxLU_2_9bUTwORCMMKwIxAV5_D1nnBepf5xEn3eGeMUf2vRpGqYUg96tWMGmo2Nc0iIUN0_gF3AM'
ADMIN_PASSWORD = "203BackstagePass!"